ran automated python 3.7 upgrade

diff --git a/mgiexec b/mgiexec
--- a/mgiexec
+++ b/mgiexec
@@ -8,20 +8,20 @@ USAGE="Usage: $0 <program to execute> [ <program's options> ]\n\n
 # test to see if no program given
 
 if [ $# -lt 1 ]; then
-	echo $USAGE
-	exit 1
+        echo $USAGE
+        exit 1
 fi
 
-CWD=`pwd`			# current working directory
+CWD=`pwd`                       # current working directory
 
-FILENAME=`basename $1`		# just the filename
-FILEPATH=`dirname $1`		# just the directory path
+FILENAME=`basename $1`          # just the filename
+FILEPATH=`dirname $1`           # just the directory path
 
 shift
 
 cd $FILEPATH
-./$FILENAME "$@"		# invoke program with each parameter quoted
-EXITCODE=$?			# catch the exit code as we'll propagate it
+./$FILENAME "$@"                # invoke program with each parameter quoted
+EXITCODE=$?                     # catch the exit code as we'll propagate it
 cd $CWD
 
 exit $EXITCODE
